/*
 * GET /api/share/:id — fetch a shared script.
 * See ./index.js for the KV binding (SHARES) this needs.
 */

function json(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json; charset=utf-8" },
  });
}

export async function onRequestGet({ params, env }) {
  if (!env.SHARES) return json({ error: "sharing_not_configured" }, 503);

  const id = String(params.id || "");
  // IDs are generated by us: short base-58-ish strings. Reject anything else
  // early so bots probing random URLs never hit KV (reads cost quota).
  if (!/^[A-Za-z0-9]{6,20}$/.test(id)) return json({ error: "not_found" }, 404);

  const raw = await env.SHARES.get(id);
  if (!raw) return json({ error: "not_found" }, 404);

  return new Response(raw, {
    status: 200,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      // Shares are immutable once created — let the edge cache them briefly
      // to save KV reads when a link is opened by many people at once.
      "Cache-Control": "public, max-age=300",
    },
  });
}
